jaffle_shop:
  target: local
  outputs:
    local:
      type: duckdb
      path: tutorial.duckdb
      schema: jaffle_shop

  # target: dev
  # outputs:
  #   dev:
  #     type: snowflake
  #     account: JZQDNAJ-QL76923
  #
  #     # User/password auth
  #     user: BSTEHYPR
  #     password: d8KLUZ7TQKcu_zMnET@pcXbV-u*hs3
  #
  #     role: ACCOUNTADMIN
  #     database: HOL_DB
  #     warehouse: COMPUTE_WH
  #     schema: JAFFLE
  #     threads: 1
  #     client_session_keep_alive: False
  #     query_tag: bste
  #
  #     # optional
  #     connect_retries: 0 # default 0
  #     connect_timeout: 10 # default: 10
  #     retry_on_database_errors: False # default: false
  #     retry_all: False  # default: false
  #     reuse_connections: False # default: false (available v1.4+)
